spring:
  application:
    name: graphql-ms

  data:
    mongodb:
      uri: ${MONGO_URL:mongodb://localhost:27017/graphqlms}

  graphql:
    graphiql:
      # Enable the GraphiQL browser UI at /graphiql
      enabled: true
    path: /graphql

server:
  port: 8080

logging:
  level:
    com.graphqlms: DEBUG
